import { motion } from 'framer-motion'
import Button from '../components/Button'
import Container from '../components/Container'
import PageIntro from '../components/PageIntro'
import SectionTitle from '../components/SectionTitle'

const principles = ['Quality', 'Consistency', 'Colour', 'Customization', 'Partnership']
const process = ['Discover', 'Develop', 'Refine', 'Deliver']
const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.55, ease: [0.22, 1, 0.36, 1] } } }

function IndustrialVisual() {
  return <motion.div initial={{ opacity: 0, clipPath: 'inset(0 0 100% 0)' }} whileInView={{ opacity: 1, clipPath: 'inset(0 0 0% 0)' }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.9, ease: [0.77, 0, 0.18, 1] }} role="img" aria-label="Abstract monochrome industrial pigment production visual" className="relative aspect-[16/9] overflow-hidden bg-[#131313]"><div className="absolute inset-0 opacity-70" style={{ backgroundImage: 'linear-gradient(90deg, transparent 0 9%, #bdbdbd 9.3% 10%, transparent 10.4% 30%, #5e5e5e 30.4% 31%, transparent 31.4% 71%, #a0a0a0 71.4% 72%, transparent 72.4%), linear-gradient(0deg, transparent 0 22%, #777 22.4% 23.2%, transparent 23.6% 59%, #bdbdbd 59.4% 60.5%, transparent 60.9%)' }} /><div className="absolute left-[13%] top-[20%] h-[52%] w-[26%] border-[13px] border-white/65" /><div className="absolute left-[47%] top-[13%] h-[70%] w-[16%] rounded-t-[48%] border-[13px] border-white/45" /><div className="absolute right-[12%] top-[28%] h-[32%] w-[25%] border-[13px] border-white/60" /><div className="absolute bottom-[20%] left-[6%] right-[6%] h-px bg-white/60" /><motion.div animate={{ x: [-20, 26, -20], rotate: [-4, 3, -4], scale: [1, 1.15, 1] }} transition={{ duration: 10, repeat: Infinity, ease: 'easeInOut' }} className="absolute -right-[4%] bottom-[-34%] h-[78%] w-[42%] rounded-[50%] bg-pigment-magenta mix-blend-screen blur-[20px]" /><motion.div animate={{ x: [10, -30, 10], y: [0, -16, 0] }} transition={{ duration: 12, repeat: Infinity, ease: 'easeInOut' }} className="absolute bottom-[-27%] left-[30%] h-[53%] w-[31%] rounded-full bg-pigment-orange mix-blend-screen blur-[26px]" /><div className="absolute inset-0 bg-[linear-gradient(120deg,rgba(255,255,255,.16),transparent_35%,rgba(0,0,0,.6))]" /></motion.div>
}

export default function About() {
  return <><PageIntro eyebrow="About NSU" title={<>BUILT AROUND COLOUR.<br />DRIVEN BY POSSIBILITY.</>} description="NSU is focused on delivering vibrant colour and pigment solutions for businesses looking to bring consistency, visual impact and distinctive colour to their products." /><Container className="pb-20 md:pb-28"><IndustrialVisual /><section className="pt-20 md:pt-28"><SectionTitle label="Our approach" number="01" title="A sharper way to think about colour." description="We begin with the intended visual outcome, then keep the conversation focused on the practical context of your product and application." /><motion.div variants={{ hidden: {}, visible: { transition: { staggerChildren: 0.08 } } }} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.25 }} className="mt-14 border-t border-black md:ml-[33.33%]"><div className="grid sm:grid-cols-2">{principles.map((principle, index) => <motion.div variants={reveal} key={principle} className="flex min-h-32 flex-col justify-between border-b border-black/15 py-5 sm:odd:border-r sm:odd:pr-5 sm:even:pl-5"><span className="text-[10px] font-bold uppercase tracking-[.16em] text-black/45">0{index + 1}</span><h3 className="text-2xl font-semibold tracking-[-.055em]">{principle}</h3></motion.div>)}</div></motion.div></section><section className="pt-20 md:pt-28"><SectionTitle label="How we work" number="02" title="From colour direction to delivery." description="A straightforward process that keeps your objectives visible at every stage." /><motion.ol initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={{ hidden: {}, visible: { transition: { staggerChildren: 0.1 } } }} className="mt-14 grid border-t border-black sm:grid-cols-2 lg:grid-cols-4">{process.map((step, index) => <motion.li variants={reveal} key={step} className="min-h-44 border-b border-black/15 py-5 sm:border-r sm:px-5 sm:first:pl-0 lg:last:border-r-0"><span className="text-sm font-medium text-pigment-magenta">0{index + 1}</span><h3 className="mt-12 text-3xl font-semibold tracking-[-.06em]">{step}</h3></motion.li>)}</motion.ol></section><motion.div initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mt-20 border-t border-black pt-7 md:mt-28"><Button to="/contact">Talk to NSU</Button></motion.div></Container></>
}
